### ISSUE TITLE
[API] Set up API authentication

### ISSUE THREAD

**Issue by Prabeshpd** [nimblehq/ic-nextjs-prabesh-dahal#10]
## Why

After logging in the application to use other features user must be authorised.

## Acceptance Criteria

- User must be authenticated before accessing API.
- If user does not have permission they  should get unauthorised error.

## Resources

- Use next auth to authenticate the API and server actions
- Create a handler function to check the authentication.
- Create a method to get token for authentication.
- Create a function to check user_id for server actions

**Comment by olivierobert** [comment]
@Prabeshpd why do we need this if we use server actions?

**Comment by Prabeshpd** [comment]
Requirement is also to create only API that can be accessed by the authorized user whose UI implementation is not there. That's why I have created this issue

**Comment by olivierobert** [comment]
If that is for API, then prefix the stories with `[API]` I have done it for this one

**Comment by tednguyendev** [comment]
Let's add "Add tests" to the "Acceptance Criteria".

**Comment by olivierobert** [comment]
@tednguyendev Adding tests is a technical requirement, so has no plan in ACs. The latter should only describe how the feature should work.

**Comment by tednguyendev** [comment]
Got it, thank you 🙏 I see [other issues](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/issues/90) have the add test so I thought it is needed
