### ISSUE TITLE
[Backend] Set a background job to run the scraping process for Google search

### ISSUE THREAD

**Issue by Prabeshpd** [nimblehq/ic-nextjs-prabesh-dahal#11]
## Why

As the requirement of the project is to scrape the google as soon as the file is uploaded. So, to run the process automatically we are setting up a job to trigger the scraping of result automatically. 

## Acceptance Criteria

- Setup a BullMQ job once the file is uploaded

## Implementation Details

- Setup a BullMQ and required packages for it
- Make a separate class that can add job to BullMQ

**Comment by olivierobert** [comment]
@Prabeshpd You will need to think about implementing an exponential delaying process to avoid being blocked by Google, i.e., add a random and increasing delay for each new job added to the background job queue.

**Comment by Prabeshpd** [comment]
@olivierobert I was thinking the same process. 😄 Will add as implementation detail.
