### ISSUE TITLE
[UI] As a user, I can view scraped information from Bing

### ISSUE THREAD

**Issue by olivierobert** [nimblehq/ic-nextjs-prabesh-dahal#118]
## Why

Once the search result page has been scraped, a user wants to see it.

## Acceptance Criteria

- In the search results list, add a column to identify each row as coming from Google or Bing
- Add a new page to view the craped information from Bing for a keyword

**Comment by Prabeshpd** [comment]
Since, the results already have a unique id I think the same page should suffice to view the detail of results. I will add the search engine value on the details. Is there anything I am missing on new page. cc @olivierobert

**Comment by olivierobert** [comment]
Both approaches would be okay. You can decide on this.
