### ISSUE TITLE
[Chore] Set up Docker compose to deploy the application

### ISSUE THREAD

**Issue by olivierobert** [nimblehq/ic-nextjs-prabesh-dahal#126]
## Why

To easily deploy the application, it must be fully containerized.

## Acceptance Criteria

- Set up a Docker Compose file for deployment: `docker-compose.yml`
- Set up service for the worker.
- Set up a service for the application. 
- Do NOT set up a service for the database as a third-party service will be used.

**Comment by Prabeshpd** [comment]
Since for worker we only require the redis instance. I believe we will use  a hosted service. We would not have service for worker. Is that OK?
