### ISSUE TITLE
[Backend] As a user, I can sign up with google

### ISSUE THREAD

**Issue by Prabeshpd** [nimblehq/ic-nextjs-prabesh-dahal#18]
## Why
User may find it hassle to sign up with providing manual user name and password. So, we would like to use the OAUTH 2.0 strategy to leverage gmail to login in to the application.

## Acceptance Criteria

- User can use Google to sign up in the applications

**Comment by olivierobert** [comment]
@Prabeshpd you will need to think about how to handle if a user tries to sign up with the same email they used to login with email + password. You can either show an error message (easier) or merge the accounts (harder). I recommend the easy option for this IC.
