### ISSUE TITLE
[Chore] Set up Docker compose for local development

### ISSUE THREAD

**Issue by Prabeshpd** [nimblehq/ic-nextjs-prabesh-dahal#23]
## Why
Setting up a Docker Compose file will help other developers start the project easily and start the development. 

## Acceptance Criteria

- Set up a Docker Compose file for local development: `docker-compose.dev.yml`
- Set up service for the database.
- Set up service for the worker.
- (Optional) Set up a service for the application. 
- Add a Makefile to start the containers (see https://makefiletutorial.com/). The command could be: `make start`

**Comment by olivierobert** [comment]
@Prabeshpd this issue was closed but this remains to be done, right?

**Comment by Prabeshpd** [comment]
> @Prabeshpd this issue was closed but this remains to be done, right?

Yes, I had created a PR. But the process was over.
