### ISSUE TITLE
[Chore] Setup CI environment to run the test

### ISSUE THREAD

**Issue by Prabeshpd** [nimblehq/ic-nextjs-prabesh-dahal#3]
## Why

Whenever a new PR is merged or created we need to check whether all the codes integrates properly or not. To test it one must create an environment and run the test written. For this we want to leverage the GitHub Actions for running the test and building the application

## Acceptance Criteria

- Create a CI pipeline that runs on PR running all the test

## Implementation Details
- Create CI so that the end to end test can be run
- Create CI so that the unit test can be run

**Comment by olivierobert** [comment]
@Prabeshpd I am unsure what the difference is between this chore and #2 . Both could be merged into one.
