### ISSUE TITLE
[Chore] Move all the test to source folder

### ISSUE THREAD

**Issue by Prabeshpd** [nimblehq/ic-nextjs-prabesh-dahal#87]
## Why

Current test resides in two places. Make sure to move the test to src folders so it follows javascript conventions

## Acceptance Criteria

- Move all the  tests to source folder file to interact with database.

**Comment by olivierobert** [comment]
@Prabeshpd This is not a high priority. It is best to target completing all features first. In addition, changing all tests at once would result in a large PR so it would be best to split this chore into multiple ones (e.g., one chore for each file type).
