### ISSUE TITLE
[Backend] As a user, I can upload a CSV file

### ISSUE THREAD

**Issue by Prabeshpd** [nimblehq/ic-nextjs-prabesh-dahal#9]
## Why

Once the CSV file is uploaded, the file must be validated whether the file has keywords more than 100. As the requirement is of 100 keywords the file must be validated. Once validated store the keywords in database as the user wants to view the keyword along with search result.

## Acceptance Criteria

- The uploaded keywords file must be validated for 100 keywords
- API to receive the file
- Testing must be in place

## Implementation Details

- API must use `multer` or other packages to get the file.
- Parse the file and validate 100 keywords
- Store the tags for the user in the database

### Table Columns

- id (Primary Key)
- user_id (References user table,  foreign key)
- keyword (string)

**Comment by olivierobert** [comment]
@Prabeshpd Primary keys should always be just `id`. No prefix or suffix needed.
