### ISSUE TITLE
[API] As a user, I can search keywords results using various queries

### ISSUE THREAD

**Issue by Prabeshpd** [nimblehq/ic-nextjs-prabesh-dahal#99]
## Why

In the requirement it is required that user can search the results using different criteria. So, an api is needed to implement such query logic.

## Acceptance Criteria

- User must be able to send query params and get the filtered result.

## Resources
-  Update the list api to get query params for searching with specific url, specific words in ad urls and specific characters on urls
- Use the existing the SearchResult Query to get the results

**Comment by tednguyendev** [comment]
You can add "Add tests" to the "Acceptance Criteria" too.
